### ISSUE TITLE
Integration Fails with HA Core 2024.1 Release

### ISSUE THREAD

**Issue by BigThunderSR** [jdeath/rd200v2#32]
Integration fails with HA Core 2024.1 release and the following error is logged:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 3:02:03 PM (2 occurrences)
Last logged: 3:02:05 PM

Error while setting up rd200_ble platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rd200_ble/sensor.py", line 132, in async_setup_entry
    val.native_unit_of_measurement = VOLUME_PICOCURIE
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'native_unit_of_measurement'
```

**Comment by jdeath** [comment]
That is annoying. I have not updated yet. I'll see if can be fixed.

**Comment by jdeath** [comment]
Fixed with https://github.com/jdeath/rd200v2/releases/tag/4.1

Reopen Issue if still a problem
