### ISSUE TITLE
Integration fails to load

### ISSUE THREAD

**Issue by HeedfulCrayon** [jdeath/rd200v2#35]
I am running Home Assistant Core version 2023.12.3

Here is the log:

```
Setup failed for custom integration 'rd200_ble': Unable to import component: cannot import name 'close_stale_connections_by_address' from 'bleak_retry_connector' (/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/rd200_ble/__init__.py", line 16, in <module>
    from bleak_retry_connector import close_stale_connections_by_address
ImportError: cannot import name 'close_stale_connections_by_address' from 'bleak_retry_connector' (/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py)
```

**Comment by jdeath** [comment]
You may need to revert to 4.1 or 4.0, or update to core 2024.1.X . I didn't realize that new function required the new homeassistant.
